# Generated by Django 4.2.7 on 2023-11-17 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="slag",
        ),
        migrations.AddField(
            model_name="menu",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=60,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Слаг меню",
            ),
        ),
    ]
